// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type LeaderboardEntry struct {
	ScrapeID int64  `json:"scrape_id"`
	Uid      int32  `json:"uid"`
	Data     []byte `json:"data"`
}

type LeaderboardScrape struct {
	ScrapeID        int64              `json:"scrape_id"`
	LeaderboardKind string             `json:"leaderboard_kind"`
	ScrapedAt       pgtype.Timestamptz `json:"scraped_at"`
}

type User struct {
	Uid      int32  `json:"uid"`
	Username string `json:"username"`
}
